launchpadlib: pull in newer version
During first login the following trace showed up, which was fixed in
LP: #1861873

    AttributeError: module 'cgi' has no attribute 'parse_qs'

Fixes #14